travis:
  secure:
    BINSTAR_TOKEN: hn5u4/L0MNJziEvO/PrspYhVjcRPHYHJMnyBpZ3b8HfywALORxVCeRKKrKDq/9jLH+OCDW9LnTXXx7e/izZsM56eUA0czyMZom+AkqtQVmyKiq3m188xvDyYqo63HvJIT10cuGUu/QZ6mAfwpKAiAstPJE2K75towj3hVdxH1dmkBJ+6uUtqwwAqd3vgEvZe7UVt1aZgbpkvhfMHGCIL5Ljk40h4sGbhfCA6doxOi4SvFXT3e/hwwoyRekLc+xhu3O4j3xsc0iQqxdhQQ91b7o2hFRYsiRU7Gh5S9s0N3uGY08jFxTxV30/W7piHIUNIs9i7Bk3w9nBMz2p/9t+PX922c7oMhDY4Q00tuE7y5YDoo6M5n2UwO4hqFfwmRcuWjDl69QZkzNfX/cbJ2/brye3ORkWsJPDupfKKfUAH6dEANV5mZUWb86f2Au8eqGmPy7y+sbB1AFFFfiV4tgswQ5u82jAkInoYjei94SAPMuKDGvLz5L9H5/uU5QgFUihZh4Gm5js12KSB5rl/2GevSPEdkSwyO/PwyUsP7Mflu74NB21xl2H/r54rH0a8RAR6Ez+kgK36+EmT1uTwled9HC3kSSMlJJDKnNqbLXPMVRRGTfFMGevE+jlHz1QycpZNAWrT+2rVzRahvTl8kumannN1ST+FN9F2fguehNGI6Gs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
